import { Theme } from '../models/Theme.js';

/* eslint-disable no-console */

/** Optimized Unsplash background — WebP when supported, 1600px wide, q=75. */
function img(id) {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1600&q=75`;
}

/**
 * 30 curated premium themes — upserted on every deploy by slug.
 * Legacy catalog themes (96 templates) remain untouched.
 */
export const PREMIUM_THEMES = [
  {
    name: 'Royal Wedding',
    slug: 'premium-royal-wedding',
    category: 'wedding',
    description: 'Regal burgundy and gold with ornate florals for grand wedding celebrations.',
    backgroundImage: img('1519741497674-05eec4c9a3e0'),
    colors: { primary: '#7f1d1d', secondary: '#991b1b', accent: '#fbbf24', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#450a0a', footerText: '#fef3c7' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Cormorant Garamond", Georgia, serif' },
    style: { decoration: 'gold-ornate', buttonStyle: 'pill-glow', iconSet: 'crown', particleStyle: 'gold-dust', gradientFrom: '#7f1d1d', gradientTo: '#fbbf24' },
    heroLabel: 'Royal Wedding Live',
    footerText: 'With love & grandeur',
    sortOrder: 1,
  },
  {
    name: 'Floral Wedding',
    slug: 'premium-floral-wedding',
    category: 'wedding',
    description: 'Soft blush florals and romantic script typography.',
    backgroundImage: img('1465496919957-b1cf01e17bb7'),
    colors: { primary: '#db2777', secondary: '#be185d', accent: '#fbcfe8', heroText: '#ffffff', surface: '#fdf2f8', footerBg: '#831843', footerText: '#fce7f3' },
    fonts: { heading: '"Dancing Script", cursive', body: '"Lora", Georgia, serif' },
    style: { decoration: 'floral', buttonStyle: 'glass', iconSet: 'flower', particleStyle: 'petals', gradientFrom: '#db2777', gradientTo: '#fbcfe8' },
    heroLabel: 'Floral Celebration',
    footerText: 'Blooming with love',
    sortOrder: 2,
  },
  {
    name: 'Luxury Gold',
    slug: 'premium-luxury-gold',
    category: 'wedding',
    description: 'Opulent champagne gold on deep charcoal for a luxe affair.',
    backgroundImage: img('1470225620782-24cfdcd21e71'),
    colors: { primary: '#b45309', secondary: '#92400e', accent: '#fde68a', heroText: '#fffbeb', surface: '#fffbeb', footerBg: '#1c1917', footerText: '#fde68a' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Playfair Display", Georgia, serif' },
    style: { decoration: 'gold-ornate', buttonStyle: 'pill-glow', iconSet: 'diamond', particleStyle: 'gold-dust', gradientFrom: '#b45309', gradientTo: '#1c1917' },
    heroLabel: 'Luxury Gold Live',
    footerText: 'Golden moments',
    sortOrder: 3,
  },
  {
    name: 'Traditional Telugu Wedding',
    slug: 'premium-traditional-telugu-wedding',
    category: 'wedding',
    description: 'Vibrant maroon and temple gold inspired by South Indian traditions.',
    backgroundImage: img('1605647543714-5c303122aec9'),
    colors: { primary: '#b91c1c', secondary: '#7f1d1d', accent: '#f59e0b', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#450a0a', footerText: '#fef3c7' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: { decoration: 'mandala', buttonStyle: 'rounded-gold', iconSet: 'lotus', particleStyle: 'gold-dust', gradientFrom: '#b91c1c', gradientTo: '#f59e0b' },
    heroLabel: 'Telugu Wedding Live',
    footerText: 'సంప్రదాయం · Tradition',
    sortOrder: 4,
  },
  {
    name: 'South Indian Temple',
    slug: 'premium-south-indian-temple',
    category: 'temple',
    description: 'Sacred saffron and temple architecture for devotional events.',
    backgroundImage: img('1583417224552-c6b5d7c4d5b0'),
    colors: { primary: '#ea580c', secondary: '#c2410c', accent: '#fbbf24', heroText: '#ffffff', surface: '#fff7ed', footerBg: '#431407', footerText: '#ffedd5' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: { decoration: 'mandala', buttonStyle: 'rounded-gold', iconSet: 'temple', particleStyle: 'gold-dust', gradientFrom: '#ea580c', gradientTo: '#fbbf24' },
    heroLabel: 'Temple Event Live',
    footerText: 'Divine blessings',
    sortOrder: 5,
  },
  {
    name: 'Hindu Wedding',
    slug: 'premium-hindu-wedding',
    category: 'wedding',
    description: 'Classic vermillion and gold for traditional Hindu ceremonies.',
    backgroundImage: img('1522673550889-84d44c25de38'),
    colors: { primary: '#dc2626', secondary: '#991b1b', accent: '#fcd34d', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#7f1d1d', footerText: '#fef3c7' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: { decoration: 'mandala', buttonStyle: 'pill-glow', iconSet: 'om', particleStyle: 'petals', gradientFrom: '#dc2626', gradientTo: '#fcd34d' },
    heroLabel: 'Hindu Wedding Live',
    footerText: 'शुभ विवाह',
    sortOrder: 6,
  },
  {
    name: 'Muslim Wedding',
    slug: 'premium-muslim-wedding',
    category: 'wedding',
    description: 'Emerald elegance with crescent motifs and refined calligraphy.',
    backgroundImage: img('1511285560929-80b456e0d9a0'),
    colors: { primary: '#047857', secondary: '#065f46', accent: '#d4af37', heroText: '#ffffff', surface: '#ecfdf5', footerBg: '#064e3b', footerText: '#d1fae5' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Lato", system-ui, sans-serif' },
    style: { decoration: 'crescent', buttonStyle: 'glass', iconSet: 'crescent', particleStyle: 'stars', gradientFrom: '#047857', gradientTo: '#d4af37' },
    heroLabel: 'Nikah Live',
    footerText: 'Barakallahu lakuma',
    sortOrder: 7,
  },
  {
    name: 'Christian Wedding',
    slug: 'premium-christian-wedding',
    category: 'wedding',
    description: 'Ivory and sapphire grace for church and chapel weddings.',
    backgroundImage: img('1519225429268-4d9bd6b9f6ef'),
    colors: { primary: '#1e40af', secondary: '#1e3a8a', accent: '#f8fafc', heroText: '#ffffff', surface: '#f8fafc', footerBg: '#1e3a8a', footerText: '#e0e7ff' },
    fonts: { heading: '"Lora", Georgia, serif', body: '"Open Sans", system-ui, sans-serif' },
    style: { decoration: 'cross', buttonStyle: 'outline-glass', iconSet: 'cross', particleStyle: 'bokeh', gradientFrom: '#1e40af', gradientTo: '#f8fafc' },
    heroLabel: 'Holy Matrimony Live',
    footerText: 'Two become one',
    sortOrder: 8,
  },
  {
    name: 'Reception Royal',
    slug: 'premium-reception-royal',
    category: 'reception',
    description: 'Purple velvet and golden chandeliers for a royal reception.',
    backgroundImage: img('1519167758481-83f550bb49b3'),
    colors: { primary: '#6b21a8', secondary: '#581c87', accent: '#fbbf24', heroText: '#ffffff', surface: '#faf5ff', footerBg: '#3b0764', footerText: '#e9d5ff' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Raleway", system-ui, sans-serif' },
    style: { decoration: 'gold-ornate', buttonStyle: 'pill-glow', iconSet: 'champagne', particleStyle: 'bokeh', gradientFrom: '#6b21a8', gradientTo: '#fbbf24' },
    heroLabel: 'Royal Reception',
    footerText: 'Celebrate in style',
    sortOrder: 9,
  },
  {
    name: 'Sangeet Neon',
    slug: 'premium-sangeet-neon',
    category: 'sangeet',
    description: 'Electric neon lights and dance-floor energy for sangeet night.',
    backgroundImage: img('1514525253161-7a46e19d933a'),
    colors: { primary: '#d946ef', secondary: '#a21caf', accent: '#22d3ee', heroText: '#ffffff', surface: '#1e1b4b', footerBg: '#0f0a1a', footerText: '#e879f9' },
    fonts: { heading: '"Montserrat", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    style: { decoration: 'neon', buttonStyle: 'neon', iconSet: 'music', particleStyle: 'neon', gradientFrom: '#d946ef', gradientTo: '#22d3ee' },
    heroLabel: 'Sangeet Night Live',
    footerText: 'Dance · Sing · Celebrate',
    sortOrder: 10,
  },
  {
    name: 'Haldi Yellow',
    slug: 'premium-haldi-yellow',
    category: 'haldi',
    description: 'Sun-kissed turmeric yellows for the haldi ceremony.',
    backgroundImage: img('1606800053565-f0b0ccf8e3a3'),
    colors: { primary: '#ca8a04', secondary: '#a16207', accent: '#fef08a', heroText: '#422006', surface: '#fefce8', footerBg: '#713f12', footerText: '#fef9c3' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Nunito", system-ui, sans-serif' },
    style: { decoration: 'sun', buttonStyle: 'rounded-gold', iconSet: 'sun', particleStyle: 'confetti', gradientFrom: '#ca8a04', gradientTo: '#fef08a' },
    heroLabel: 'Haldi Ceremony Live',
    footerText: 'Turmeric blessings',
    sortOrder: 11,
  },
  {
    name: 'Mehendi Green',
    slug: 'premium-mehendi-green',
    category: 'mehendi',
    description: 'Rich mehendi greens with intricate henna-inspired accents.',
    backgroundImage: img('1515934757279-8b27defc6c67'),
    colors: { primary: '#15803d', secondary: '#166534', accent: '#86efac', heroText: '#ffffff', surface: '#f0fdf4', footerBg: '#14532d', footerText: '#bbf7d0' },
    fonts: { heading: '"Dancing Script", cursive', body: '"Lora", Georgia, serif' },
    style: { decoration: 'henna', buttonStyle: 'glass', iconSet: 'leaf', particleStyle: 'leaves', gradientFrom: '#15803d', gradientTo: '#86efac' },
    heroLabel: 'Mehendi Live',
    footerText: 'Henna & harmony',
    sortOrder: 12,
  },
  {
    name: 'Birthday Kids',
    slug: 'premium-birthday-kids',
    category: 'birthday',
    description: 'Playful rainbow colors and confetti for kids birthday parties.',
    backgroundImage: img('1530103862677-6be7f886aefc'),
    colors: { primary: '#2563eb', secondary: '#7c3aed', accent: '#f472b6', heroText: '#ffffff', surface: '#eff6ff', footerBg: '#1e3a8a', footerText: '#bfdbfe' },
    fonts: { heading: '"Nunito", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    style: { decoration: 'confetti', buttonStyle: 'pill-glow', iconSet: 'balloon', particleStyle: 'confetti', gradientFrom: '#2563eb', gradientTo: '#f472b6' },
    heroLabel: 'Birthday Party Live',
    footerText: 'Let\'s party!',
    sortOrder: 13,
  },
  {
    name: 'Birthday Princess',
    slug: 'premium-birthday-princess',
    category: 'birthday',
    description: 'Fairy-tale pink and sparkle for a princess celebration.',
    backgroundImage: img('1558636508-0f6edbe6d7d1'),
    colors: { primary: '#ec4899', secondary: '#db2777', accent: '#f9a8d4', heroText: '#ffffff', surface: '#fdf2f8', footerBg: '#831843', footerText: '#fce7f3' },
    fonts: { heading: '"Dancing Script", cursive', body: '"Nunito", system-ui, sans-serif' },
    style: { decoration: 'crown', buttonStyle: 'glass', iconSet: 'crown', particleStyle: 'stars', gradientFrom: '#ec4899', gradientTo: '#f9a8d4' },
    heroLabel: 'Princess Birthday Live',
    footerText: 'Once upon a dream',
    sortOrder: 14,
  },
  {
    name: 'Birthday Superhero',
    slug: 'premium-birthday-superhero',
    category: 'birthday',
    description: 'Bold comic-book colors for superhero-themed birthdays.',
    backgroundImage: img('1504196606672-f4d3c5b1c8c0'),
    colors: { primary: '#dc2626', secondary: '#1d4ed8', accent: '#fbbf24', heroText: '#ffffff', surface: '#eff6ff', footerBg: '#1e3a8a', footerText: '#fde68a' },
    fonts: { heading: '"Montserrat", system-ui, sans-serif', body: '"Roboto", system-ui, sans-serif' },
    style: { decoration: 'comic', buttonStyle: 'sharp', iconSet: 'bolt', particleStyle: 'stars', gradientFrom: '#dc2626', gradientTo: '#1d4ed8' },
    heroLabel: 'Superhero Birthday Live',
    footerText: 'To the rescue!',
    sortOrder: 15,
  },
  {
    name: 'Baby Shower',
    slug: 'premium-baby-shower',
    category: 'baby_shower',
    description: 'Soft pastels and gentle bubbles for baby shower joy.',
    backgroundImage: img('1555251364-287241e637a4'),
    colors: { primary: '#38bdf8', secondary: '#0ea5e9', accent: '#fbcfe8', heroText: '#ffffff', surface: '#f0f9ff', footerBg: '#0c4a6e', footerText: '#e0f2fe' },
    fonts: { heading: '"Nunito", system-ui, sans-serif', body: '"Open Sans", system-ui, sans-serif' },
    style: { decoration: 'bubbles', buttonStyle: 'glass', iconSet: 'baby', particleStyle: 'bubbles', gradientFrom: '#38bdf8', gradientTo: '#fbcfe8' },
    heroLabel: 'Baby Shower Live',
    footerText: 'Little one on the way',
    sortOrder: 16,
  },
  {
    name: 'Naming Ceremony',
    slug: 'premium-naming-ceremony',
    category: 'baby_shower',
    description: 'Lavender serenity for naamkaran and naming rituals.',
    backgroundImage: img('1515488764272-fb2a1d0563b5'),
    colors: { primary: '#7c3aed', secondary: '#6d28d9', accent: '#c4b5fd', heroText: '#ffffff', surface: '#f5f3ff', footerBg: '#4c1d95', footerText: '#ede9fe' },
    fonts: { heading: '"Lora", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: { decoration: 'minimal', buttonStyle: 'outline-glass', iconSet: 'star', particleStyle: 'bokeh', gradientFrom: '#7c3aed', gradientTo: '#c4b5fd' },
    heroLabel: 'Naming Ceremony Live',
    footerText: 'A new name, a new blessing',
    sortOrder: 17,
  },
  {
    name: 'Engagement',
    slug: 'premium-engagement',
    category: 'engagement',
    description: 'Rose gold romance for engagement celebrations.',
    backgroundImage: img('1520854221256-17451d7e9b6c'),
    colors: { primary: '#e11d48', secondary: '#be123c', accent: '#fda4af', heroText: '#ffffff', surface: '#fff1f2', footerBg: '#881337', footerText: '#ffe4e6' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Lato", system-ui, sans-serif' },
    style: { decoration: 'rings', buttonStyle: 'pill-glow', iconSet: 'rings', particleStyle: 'petals', gradientFrom: '#e11d48', gradientTo: '#fda4af' },
    heroLabel: 'Engagement Live',
    footerText: 'Forever begins today',
    sortOrder: 18,
  },
  {
    name: 'Anniversary',
    slug: 'premium-anniversary',
    category: 'wedding',
    description: 'Ruby wine tones celebrating years of togetherness.',
    backgroundImage: img('1464366400600-56608e6c1a3a'),
    colors: { primary: '#9f1239', secondary: '#881337', accent: '#fb7185', heroText: '#ffffff', surface: '#fff1f2', footerBg: '#4c0519', footerText: '#fecdd3' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: { decoration: 'elegant', buttonStyle: 'glass', iconSet: 'heart', particleStyle: 'bokeh', gradientFrom: '#9f1239', gradientTo: '#fb7185' },
    heroLabel: 'Anniversary Live',
    footerText: 'Years of love',
    sortOrder: 19,
  },
  {
    name: 'Corporate Event',
    slug: 'premium-corporate-event',
    category: 'corporate',
    description: 'Clean navy and silver for professional corporate gatherings.',
    backgroundImage: img('1542744173-8e7e53415bb0'),
    colors: { primary: '#1e3a8a', secondary: '#1e40af', accent: '#94a3b8', heroText: '#ffffff', surface: '#f8fafc', footerBg: '#0f172a', footerText: '#cbd5e1' },
    fonts: { heading: '"Montserrat", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    style: { decoration: 'geometric', buttonStyle: 'sharp', iconSet: 'briefcase', particleStyle: 'none', gradientFrom: '#1e3a8a', gradientTo: '#0f172a' },
    heroLabel: 'Corporate Live',
    footerText: 'Excellence in every moment',
    sortOrder: 20,
  },
  {
    name: 'Live Concert',
    slug: 'premium-live-concert',
    category: 'corporate',
    description: 'Stage lights and electric purple for live concert streaming.',
    backgroundImage: img('1470229722913-7c0e2dbbafd3'),
    colors: { primary: '#7c3aed', secondary: '#5b21b6', accent: '#f472b6', heroText: '#ffffff', surface: '#1e1b4b', footerBg: '#0f0a1a', footerText: '#c4b5fd' },
    fonts: { heading: '"Raleway", system-ui, sans-serif', body: '"Roboto", system-ui, sans-serif' },
    style: { decoration: 'neon', buttonStyle: 'neon', iconSet: 'music', particleStyle: 'neon', gradientFrom: '#7c3aed', gradientTo: '#f472b6' },
    heroLabel: 'Live Concert',
    footerText: 'Feel the beat',
    sortOrder: 21,
  },
  {
    name: 'Conference',
    slug: 'premium-conference',
    category: 'corporate',
    description: 'Modern blue-gray minimalism for conferences and summits.',
    backgroundImage: img('1556761175-5973dc0f32ed'),
    colors: { primary: '#0369a1', secondary: '#0c4a6e', accent: '#38bdf8', heroText: '#ffffff', surface: '#f0f9ff', footerBg: '#082f49', footerText: '#bae6fd' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Work Sans", system-ui, sans-serif' },
    style: { decoration: 'minimal', buttonStyle: 'outline-glass', iconSet: 'mic', particleStyle: 'dust', gradientFrom: '#0369a1', gradientTo: '#082f49' },
    heroLabel: 'Conference Live',
    footerText: 'Ideas that inspire',
    sortOrder: 22,
  },
  {
    name: 'Housewarming',
    slug: 'premium-housewarming',
    category: 'house_warming',
    description: 'Warm earth tones and cozy ambiance for griha pravesh.',
    backgroundImage: img('1560448204-e4f5cf470e0d'),
    colors: { primary: '#b45309', secondary: '#92400e', accent: '#fcd34d', heroText: '#ffffff', surface: '#fffbeb', footerBg: '#451a03', footerText: '#fde68a' },
    fonts: { heading: '"Lora", Georgia, serif', body: '"Open Sans", system-ui, sans-serif' },
    style: { decoration: 'home', buttonStyle: 'rounded-gold', iconSet: 'home', particleStyle: 'leaves', gradientFrom: '#b45309', gradientTo: '#fcd34d' },
    heroLabel: 'Housewarming Live',
    footerText: 'Home sweet home',
    sortOrder: 23,
  },
  {
    name: 'Graduation',
    slug: 'premium-graduation',
    category: 'corporate',
    description: 'Academic navy and gold for graduation ceremonies.',
    backgroundImage: img('1523050853484-6228be76d0f5'),
    colors: { primary: '#1e3a8a', secondary: '#172554', accent: '#fbbf24', heroText: '#ffffff', surface: '#eff6ff', footerBg: '#0f172a', footerText: '#fde68a' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: { decoration: 'academic', buttonStyle: 'pill-glow', iconSet: 'cap', particleStyle: 'stars', gradientFrom: '#1e3a8a', gradientTo: '#fbbf24' },
    heroLabel: 'Graduation Live',
    footerText: 'The future is yours',
    sortOrder: 24,
  },
  {
    name: 'Modern Black',
    slug: 'premium-modern-black',
    category: 'wedding',
    description: 'Sleek monochrome black and white contemporary elegance.',
    backgroundImage: img('1497366216543-37526070297c'),
    colors: { primary: '#18181b', secondary: '#27272a', accent: '#fafafa', heroText: '#ffffff', surface: '#fafafa', footerBg: '#09090b', footerText: '#e4e4e7' },
    fonts: { heading: '"Montserrat", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    style: { decoration: 'minimal', buttonStyle: 'sharp', iconSet: 'diamond', particleStyle: 'bokeh', gradientFrom: '#18181b', gradientTo: '#52525b' },
    heroLabel: 'Modern Live',
    footerText: 'Less is more',
    sortOrder: 25,
  },
  {
    name: 'Minimal White',
    slug: 'premium-minimal-white',
    category: 'wedding',
    description: 'Airy whites and soft gray for understated luxury.',
    backgroundImage: img('1497366754035-0463913a487f'),
    colors: { primary: '#64748b', secondary: '#475569', accent: '#f8fafc', heroText: '#1e293b', surface: '#ffffff', footerBg: '#334155', footerText: '#f1f5f9' },
    fonts: { heading: '"Raleway", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    style: { decoration: 'minimal', buttonStyle: 'outline-glass', iconSet: 'feather', particleStyle: 'none', gradientFrom: '#f8fafc', gradientTo: '#cbd5e1' },
    heroLabel: 'Minimal Live',
    footerText: 'Pure & simple',
    sortOrder: 26,
  },
  {
    name: 'Luxury Dark',
    slug: 'premium-luxury-dark',
    category: 'wedding',
    description: 'Midnight noir with brushed gold accents.',
    backgroundImage: img('1511795409834-ef04bbd61622'),
    colors: { primary: '#a16207', secondary: '#78350f', accent: '#fde68a', heroText: '#fef3c7', surface: '#1c1917', footerBg: '#0c0a09', footerText: '#fde68a' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Playfair Display", Georgia, serif' },
    style: { decoration: 'gold-ornate', buttonStyle: 'pill-glow', iconSet: 'diamond', particleStyle: 'gold-dust', gradientFrom: '#0c0a09', gradientTo: '#a16207' },
    heroLabel: 'Luxury Dark Live',
    footerText: 'After dark elegance',
    sortOrder: 27,
  },
  {
    name: 'Nature Theme',
    slug: 'premium-nature-theme',
    category: 'wedding',
    description: 'Forest greens and organic textures for outdoor celebrations.',
    backgroundImage: img('1441974231531-c6227db76b6e'),
    colors: { primary: '#166534', secondary: '#14532d', accent: '#86efac', heroText: '#ffffff', surface: '#f0fdf4', footerBg: '#052e16', footerText: '#bbf7d0' },
    fonts: { heading: '"Lora", Georgia, serif', body: '"Nunito", system-ui, sans-serif' },
    style: { decoration: 'leaves', buttonStyle: 'glass', iconSet: 'leaf', particleStyle: 'leaves', gradientFrom: '#166534', gradientTo: '#86efac' },
    heroLabel: 'Nature Celebration Live',
    footerText: 'Rooted in love',
    sortOrder: 28,
  },
  {
    name: 'Beach Theme',
    slug: 'premium-beach-theme',
    category: 'wedding',
    description: 'Ocean aqua and sandy neutrals for coastal weddings.',
    backgroundImage: img('1507525428034-7237b4bb55a2'),
    colors: { primary: '#0891b2', secondary: '#0e7490', accent: '#fde68a', heroText: '#ffffff', surface: '#ecfeff', footerBg: '#164e63', footerText: '#a5f3fc' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Open Sans", system-ui, sans-serif' },
    style: { decoration: 'waves', buttonStyle: 'glass', iconSet: 'wave', particleStyle: 'bubbles', gradientFrom: '#0891b2', gradientTo: '#fde68a' },
    heroLabel: 'Beach Wedding Live',
    footerText: 'Seaside vows',
    sortOrder: 29,
  },
  {
    name: 'Cinematic Theme',
    slug: 'premium-cinematic-theme',
    category: 'wedding',
    description: 'Film-noir drama with crimson accents and letterbox flair.',
    backgroundImage: img('1485846234006-7f723cf95d6b'),
    colors: { primary: '#991b1b', secondary: '#450a0a', accent: '#f87171', heroText: '#ffffff', surface: '#1c1917', footerBg: '#0c0a09', footerText: '#fca5a5' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: { decoration: 'cinematic', buttonStyle: 'sharp', iconSet: 'film', particleStyle: 'dust', gradientFrom: '#450a0a', gradientTo: '#991b1b' },
    heroLabel: 'Cinematic Live',
    footerText: 'Your story on screen',
    sortOrder: 30,
  },
];

export async function seedPremiumThemes() {
  let upserted = 0;
  for (const doc of PREMIUM_THEMES) {
    const payload = {
      ...doc,
      isPremium: true,
      isActive: true,
    };
    const existing = await Theme.findOne({ slug: doc.slug });
    if (existing) {
      Object.assign(existing, payload);
      await existing.save();
    } else {
      await Theme.create(payload);
    }
    upserted += 1;
  }
  console.log(`[seed] Premium themes upserted: ${upserted}.`);
}
