import { Theme } from '../models/Theme.js';

/* eslint-disable no-console */

function img(id) {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1600&q=75`;
}

const BUTTON_STYLES = ['pill-glow', 'glass', 'rounded-gold', 'outline-glass', 'sharp'];
const LOADING_ANIMS = ['lotus-spin', 'temple-glow', 'floral-pulse', 'gold-shimmer', 'wave'];

function regionalStyle(i, decoration, iconSet, particleStyle, gradientFrom, gradientTo, extras = {}) {
  return {
    decoration,
    buttonStyle: BUTTON_STYLES[i % BUTTON_STYLES.length],
    iconSet,
    particleStyle,
    gradientFrom,
    gradientTo,
    goldBorder: true,
    loadingAnimation: LOADING_ANIMS[i % LOADING_ANIMS.length],
    backgroundMusic: extras.backgroundMusic || '',
  };
}

/**
 * 20 South Indian regional premium themes — upserted on every deploy by slug.
 */
export const REGIONAL_THEMES = [
  // ── TELANGANA ──────────────────────────────────────────────
  {
    name: 'Telangana Traditional Wedding',
    slug: 'regional-telangana-traditional-wedding',
    category: 'wedding',
    region: 'telangana',
    description: 'Authentic Telangana maroon, gold zari, and temple florals for traditional pelli.',
    backgroundImage: img('1605647543714-5c303122aec9'),
    colors: { primary: '#991b1b', secondary: '#7f1d1d', accent: '#fbbf24', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#450a0a', footerText: '#fef3c7' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: regionalStyle(0, 'mandala', 'lotus', 'gold-dust', '#991b1b', '#fbbf24'),
    heroLabel: 'తెలంగాణ పెళ్లి Live',
    footerText: 'తెలంగాణ సంప్రదాయం',
    sortOrder: 31,
  },
  {
    name: 'Pelli Pandiri Theme',
    slug: 'regional-pelli-pandiri',
    category: 'wedding',
    region: 'telangana',
    description: 'Festive pandiri canopy colours with marigold garlands and celebratory gold.',
    backgroundImage: img('1515934757279-8b27defc6c67'),
    colors: { primary: '#c2410c', secondary: '#9a3412', accent: '#fde047', heroText: '#ffffff', surface: '#fff7ed', footerBg: '#431407', footerText: '#ffedd5' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: regionalStyle(1, 'floral', 'flower', 'petals', '#c2410c', '#fde047'),
    heroLabel: 'పెళ్లి పందిరి Live',
    footerText: 'పందిరి ఆశీర్వాదాలు',
    sortOrder: 32,
  },
  {
    name: 'Pelli Poola Theme',
    slug: 'regional-pelli-poola',
    category: 'wedding',
    region: 'telangana',
    description: 'Delicate poola jada florals in blush rose and jasmine white.',
    backgroundImage: img('1465496919957-b1cf01e17bb7'),
    colors: { primary: '#be185d', secondary: '#9d174d', accent: '#fbcfe8', heroText: '#ffffff', surface: '#fdf2f8', footerBg: '#831843', footerText: '#fce7f3' },
    fonts: { heading: '"Dancing Script", cursive', body: '"Cormorant Garamond", Georgia, serif' },
    style: regionalStyle(2, 'floral', 'flower', 'petals', '#be185d', '#fbcfe8'),
    heroLabel: 'పూల పెళ్లి Live',
    footerText: 'పూల తోరణం',
    sortOrder: 33,
  },
  {
    name: 'Royal Telangana Theme',
    slug: 'regional-royal-telangana',
    category: 'wedding',
    region: 'telangana',
    description: 'Nizam-era royal burgundy, antique gold borders, and regal typography.',
    backgroundImage: img('1519741497674-05eec4c9a3e0'),
    colors: { primary: '#7f1d1d', secondary: '#581c87', accent: '#eab308', heroText: '#fffbeb', surface: '#fef2f2', footerBg: '#1c1917', footerText: '#fde68a' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Playfair Display", Georgia, serif' },
    style: regionalStyle(3, 'gold-ornate', 'crown', 'gold-dust', '#7f1d1d', '#eab308'),
    heroLabel: 'Royal Telangana Live',
    footerText: 'రాజరాజ్య శ్రీ',
    sortOrder: 34,
  },
  {
    name: 'Temple Wedding Theme',
    slug: 'regional-telangana-temple-wedding',
    category: 'temple',
    region: 'telangana',
    description: 'Sacred temple gopuram backdrop with saffron and turmeric accents.',
    backgroundImage: img('1583417224552-c6b5d7c4d5b0'),
    colors: { primary: '#ea580c', secondary: '#c2410c', accent: '#fbbf24', heroText: '#ffffff', surface: '#fff7ed', footerBg: '#431407', footerText: '#ffedd5' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: regionalStyle(4, 'mandala', 'temple', 'gold-dust', '#ea580c', '#fbbf24'),
    heroLabel: 'Temple Wedding Live',
    footerText: 'దేవాలయ వివాహం',
    sortOrder: 35,
  },

  // ── ANDHRA PRADESH ─────────────────────────────────────────
  {
    name: 'Andhra Traditional Wedding',
    slug: 'regional-andhra-traditional-wedding',
    category: 'wedding',
    region: 'andhra',
    description: 'Classic Andhra red kanchi, mango leaf toranam, and golden kalash motifs.',
    backgroundImage: img('1522673550889-84d44c25de38'),
    colors: { primary: '#dc2626', secondary: '#991b1b', accent: '#fcd34d', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#7f1d1d', footerText: '#fef3c7' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: regionalStyle(0, 'mandala', 'om', 'petals', '#dc2626', '#fcd34d'),
    heroLabel: 'ఆంధ్ర పెళ్లి Live',
    footerText: 'ఆంధ్ర సంప్రదాయం',
    sortOrder: 36,
  },
  {
    name: 'Tirupati Style Theme',
    slug: 'regional-tirupati-style',
    category: 'temple',
    region: 'andhra',
    description: 'Tirumala-inspired saffron, white, and sacred gold for divine celebrations.',
    backgroundImage: img('1605647543714-5c303122aec9'),
    colors: { primary: '#ea580c', secondary: '#c2410c', accent: '#fef3c7', heroText: '#ffffff', surface: '#fffbeb', footerBg: '#78350f', footerText: '#fde68a' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: regionalStyle(1, 'mandala', 'temple', 'gold-dust', '#ea580c', '#fef3c7'),
    heroLabel: 'తిరుపతి శైలి Live',
    footerText: 'గోవిందా నామం',
    sortOrder: 37,
  },
  {
    name: 'Godavari Floral Theme',
    slug: 'regional-godavari-floral',
    category: 'wedding',
    region: 'andhra',
    description: 'Lush Godavari delta greens with jasmine and marigold riverbank florals.',
    backgroundImage: img('1441974231531-c6227db76b6e'),
    colors: { primary: '#15803d', secondary: '#166534', accent: '#fde047', heroText: '#ffffff', surface: '#f0fdf4', footerBg: '#14532d', footerText: '#bbf7d0' },
    fonts: { heading: '"Lora", Georgia, serif', body: '"Nunito", system-ui, sans-serif' },
    style: regionalStyle(2, 'floral', 'leaf', 'leaves', '#15803d', '#fde047'),
    heroLabel: 'గోదావరి పూల Live',
    footerText: 'గోదావరి ఆశీర్వాదాలు',
    sortOrder: 38,
  },
  {
    name: 'Royal Andhra Theme',
    slug: 'regional-royal-andhra',
    category: 'wedding',
    region: 'andhra',
    description: 'Vijayanagara-inspired crimson and antique gold for grand Andhra weddings.',
    backgroundImage: img('1470225620782-24cfdcd21e71'),
    colors: { primary: '#b91c1c', secondary: '#7f1d1d', accent: '#fbbf24', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#450a0a', footerText: '#fef3c7' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Cormorant Garamond", Georgia, serif' },
    style: regionalStyle(3, 'gold-ornate', 'crown', 'gold-dust', '#b91c1c', '#fbbf24'),
    heroLabel: 'Royal Andhra Live',
    footerText: 'ఆంధ్ర మహారాజ్యం',
    sortOrder: 39,
  },
  {
    name: 'Classic Telugu Wedding Theme',
    slug: 'regional-classic-telugu-wedding',
    category: 'wedding',
    region: 'andhra',
    description: 'Timeless Telugu wedding palette with turmeric yellow and kumkum red.',
    backgroundImage: img('1606800053565-f0b0ccf8e3a3'),
    colors: { primary: '#ca8a04', secondary: '#b91c1c', accent: '#fde68a', heroText: '#422006', surface: '#fffbeb', footerBg: '#713f12', footerText: '#fef9c3' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: regionalStyle(4, 'floral', 'rings', 'confetti', '#ca8a04', '#b91c1c'),
    heroLabel: 'తెలుగు పెళ్లి Live',
    footerText: 'శుభ వివాహం',
    sortOrder: 40,
  },

  // ── TAMIL NADU ─────────────────────────────────────────────
  {
    name: 'Tamil Brahmin Wedding',
    slug: 'regional-tamil-brahmin-wedding',
    category: 'wedding',
    region: 'tamil_nadu',
    description: 'Iyer tradition with manai palagai white, turmeric, and sacred red kumkum.',
    backgroundImage: img('1519225429268-4d9bd6b9f6ef'),
    colors: { primary: '#b91c1c', secondary: '#fef3c7', accent: '#fcd34d', heroText: '#ffffff', surface: '#fffbeb', footerBg: '#7f1d1d', footerText: '#fef3c7' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: regionalStyle(0, 'mandala', 'om', 'gold-dust', '#b91c1c', '#fcd34d'),
    heroLabel: 'தமிழ் பிராமண திருமணம் Live',
    footerText: 'சுப விவாகம்',
    sortOrder: 41,
  },
  {
    name: 'Madurai Temple Theme',
    slug: 'regional-madurai-temple',
    category: 'temple',
    region: 'tamil_nadu',
    description: 'Meenakshi Amman temple architecture with Dravidian gold and stone hues.',
    backgroundImage: img('1583417224552-c6b5d7c4d5b0'),
    colors: { primary: '#b45309', secondary: '#78350f', accent: '#fde68a', heroText: '#ffffff', surface: '#fffbeb', footerBg: '#451a03', footerText: '#fde68a' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: regionalStyle(1, 'mandala', 'temple', 'gold-dust', '#b45309', '#fde68a'),
    heroLabel: 'மதுரை கோவில் Live',
    footerText: 'அருள்மிகு திருமணம்',
    sortOrder: 42,
  },
  {
    name: 'Chettinad Royal Theme',
    slug: 'regional-chettinad-royal',
    category: 'wedding',
    region: 'tamil_nadu',
    description: 'Chettinad mansion reds, Athangudi tile patterns, and antique brass gold.',
    backgroundImage: img('1560448204-e4f5cf470e0d'),
    colors: { primary: '#9f1239', secondary: '#881337', accent: '#fbbf24', heroText: '#ffffff', surface: '#fff1f2', footerBg: '#4c0519', footerText: '#fecdd3' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Cormorant Garamond", Georgia, serif' },
    style: regionalStyle(2, 'gold-ornate', 'crown', 'gold-dust', '#9f1239', '#fbbf24'),
    heroLabel: 'செட்டிநாடு ராஜ்ய Live',
    footerText: 'செட்டிநாடு வைபவம்',
    sortOrder: 43,
  },
  {
    name: 'Kanchipuram Silk Theme',
    slug: 'regional-kanchipuram-silk',
    category: 'wedding',
    region: 'tamil_nadu',
    description: 'Kanjivaram silk green and temple gold with zari border elegance.',
    backgroundImage: img('1511285560929-80b456e0d9a0'),
    colors: { primary: '#166534', secondary: '#14532d', accent: '#fbbf24', heroText: '#ffffff', surface: '#f0fdf4', footerBg: '#052e16', footerText: '#bbf7d0' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: regionalStyle(3, 'floral', 'lotus', 'petals', '#166534', '#fbbf24'),
    heroLabel: 'காஞ்சிபுரம் பட்டு Live',
    footerText: 'பட்டு திருமணம்',
    sortOrder: 44,
  },
  {
    name: 'Traditional Tamil Wedding Theme',
    slug: 'regional-traditional-tamil-wedding',
    category: 'wedding',
    region: 'tamil_nadu',
    description: 'Classic Tamil muhurtham with nadaswaram reds and mango leaf decor.',
    backgroundImage: img('1520854221256-17451d7e9b6c'),
    colors: { primary: '#dc2626', secondary: '#991b1b', accent: '#86efac', heroText: '#ffffff', surface: '#fef2f2', footerBg: '#7f1d1d', footerText: '#fecaca' },
    fonts: { heading: '"Merriweather", Georgia, serif', body: '"Source Sans 3", system-ui, sans-serif' },
    style: regionalStyle(4, 'floral', 'flower', 'petals', '#dc2626', '#86efac'),
    heroLabel: 'தமிழ் திருமணம் Live',
    footerText: 'மங்களம்',
    sortOrder: 45,
  },

  // ── KERALA ─────────────────────────────────────────────────
  {
    name: 'Kerala Hindu Wedding',
    slug: 'regional-kerala-hindu-wedding',
    category: 'wedding',
    region: 'kerala',
    description: 'Kerala Hindu tradition with kasavu cream, gold kasavu borders, and temple lamps.',
    backgroundImage: img('1583417224552-c6b5d7c4d5b0'),
    colors: { primary: '#b45309', secondary: '#fef3c7', accent: '#fbbf24', heroText: '#422006', surface: '#fffbeb', footerBg: '#78350f', footerText: '#fde68a' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Lora", Georgia, serif' },
    style: regionalStyle(0, 'gold-ornate', 'om', 'gold-dust', '#b45309', '#fef3c7'),
    heroLabel: 'കേരള ഹിന്ദു വിവാഹം Live',
    footerText: 'ശുഭ വിവാഹം',
    sortOrder: 46,
  },
  {
    name: 'Kerala Nair Wedding',
    slug: 'regional-kerala-nair-wedding',
    category: 'wedding',
    region: 'kerala',
    description: 'Nair community elegance with ivory mundu, gold jewellery tones, and jasmine.',
    backgroundImage: img('1515488764272-fb2a1d0563b5'),
    colors: { primary: '#fef3c7', secondary: '#d97706', accent: '#fbbf24', heroText: '#422006', surface: '#fffbeb', footerBg: '#92400e', footerText: '#fde68a' },
    fonts: { heading: '"Playfair Display", Georgia, serif', body: '"Cormorant Garamond", Georgia, serif' },
    style: regionalStyle(1, 'floral', 'flower', 'petals', '#d97706', '#fef3c7'),
    heroLabel: 'നായർ വിവാഹം Live',
    footerText: 'നായർ പാരമ്പര്യം',
    sortOrder: 47,
  },
  {
    name: 'Guruvayur Temple Theme',
    slug: 'regional-guruvayur-temple',
    category: 'temple',
    region: 'kerala',
    description: 'Guruvayur temple sanctum colours with deep ochre and sacred gold.',
    backgroundImage: img('1605647543714-5c303122aec9'),
    colors: { primary: '#c2410c', secondary: '#9a3412', accent: '#fde68a', heroText: '#ffffff', surface: '#fff7ed', footerBg: '#431407', footerText: '#ffedd5' },
    fonts: { heading: '"Cinzel", Georgia, serif', body: '"Merriweather", Georgia, serif' },
    style: regionalStyle(2, 'mandala', 'temple', 'gold-dust', '#c2410c', '#fde68a'),
    heroLabel: 'ഗുരുവായൂർ ക്ഷേത്രം Live',
    footerText: 'ഗുരുവായൂർപ്പാൻ',
    sortOrder: 48,
  },
  {
    name: 'Kerala Floral Theme',
    slug: 'regional-kerala-floral',
    category: 'wedding',
    region: 'kerala',
    description: 'Pookkalam jasmine whites, coconut palm greens, and Onam floral abundance.',
    backgroundImage: img('1441974231531-c6227db76b6e'),
    colors: { primary: '#15803d', secondary: '#fefce8', accent: '#ffffff', heroText: '#ffffff', surface: '#f0fdf4', footerBg: '#14532d', footerText: '#bbf7d0' },
    fonts: { heading: '"Dancing Script", cursive', body: '"Nunito", system-ui, sans-serif' },
    style: regionalStyle(3, 'floral', 'leaf', 'leaves', '#15803d', '#fefce8'),
    heroLabel: 'കേരള പുഷ്പം Live',
    footerText: 'പൂക്കളം',
    sortOrder: 49,
  },
  {
    name: 'Backwater Luxury Theme',
    slug: 'regional-backwater-luxury',
    category: 'wedding',
    region: 'kerala',
    description: 'Alleppey backwater teal, houseboat luxury, and sunset gold reflections.',
    backgroundImage: img('1507525428034-7237b4bb55a2'),
    colors: { primary: '#0e7490', secondary: '#164e63', accent: '#fde68a', heroText: '#ffffff', surface: '#ecfeff', footerBg: '#083344', footerText: '#a5f3fc' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Poppins", system-ui, sans-serif' },
    style: regionalStyle(4, 'waves', 'wave', 'bubbles', '#0e7490', '#fde68a'),
    heroLabel: 'ബാക്ക്‌വാട്ടർ ലക്ഷ്വറി Live',
    footerText: 'കായല്‍ വിവാഹം',
    sortOrder: 50,
  },
];

export async function seedRegionalThemes() {
  let upserted = 0;
  for (const doc of REGIONAL_THEMES) {
    const payload = { ...doc, isPremium: true, isActive: true };
    const existing = await Theme.findOne({ slug: doc.slug });
    if (existing) {
      Object.assign(existing, payload);
      await existing.save();
    } else {
      await Theme.create(payload);
    }
    upserted += 1;
  }
  console.log(`[seed] Regional themes upserted: ${upserted}.`);
}
